"use strict";

// Shared primitives for reading the knowledge graph and comparing it against the corpus.
//
// The load-bearing idea: `graphify-out/graph.json` is a POST-BUILD serialization. networkx has
// already absorbed duplicate and collapsed edges by the time it is written, and `graphify
// diagnose` says so itself — "a normal graph.json is already post-build and cannot recover raw
// producer edges". So a graph that is internally consistent can still be badly wrong. Every check
// worth running compares the graph to the corpus, never to itself.

const { execFileSync } = require("node:child_process");
const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

// Node IDs follow graphify's documented rule (references/extraction-spec.md): the full
// repo-relative path with the extension dropped, every segment kept, each segment lowercased with
// non-alphanumerics replaced by `_`, joined with `_`. Keeping every directory level is what makes
// same-named files in different directories distinct.
function stemFor(relPath) {
  const withoutExt = relPath.replace(/\.[^./]+$/, "");
  return withoutExt
    .split("/")
    .map((segment) => segment.toLowerCase().replace(/[^a-z0-9]+/g, "_"))
    .join("_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "");
}

function loadGraph(graphPath) {
  const raw = fs.readFileSync(graphPath, "utf8");
  const data = JSON.parse(raw);
  return {
    nodes: Array.isArray(data.nodes) ? data.nodes : [],
    links: Array.isArray(data.links) ? data.links : [],
    raw: data,
  };
}

function gitLines(args, cwd) {
  try {
    const out = execFileSync("git", args, { cwd, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
    return out.split("\n").filter(Boolean);
  } catch {
    return [];
  }
}

// Tracked Markdown, excluding the graph's own output — GRAPH_REPORT.md is generated by the build
// being checked, so counting it as corpus would make every graph permanently stale against itself.
function trackedMarkdown(rootDir) {
  return gitLines(["ls-files", "*.md"], rootDir).filter((p) => !p.startsWith("graphify-out/"));
}

// Strip fenced code blocks before scanning for links. A fenced example of a broken link is not a
// link, and `validate.sh` makes the same distinction.
function stripFences(text) {
  const out = [];
  let fenced = false;
  for (const line of text.split("\n")) {
    if (line.trim().startsWith("```")) {
      fenced = !fenced;
      out.push("");
      continue;
    }
    out.push(fenced ? "" : line);
  }
  return out.join("\n");
}

// Every relative Markdown link from `relPath` that resolves to another tracked file in the repo.
// Absolute paths, URLs and pure `#anchor` links are not corpus edges.
function outboundLinks(rootDir, relPath, trackedSet) {
  const abs = path.join(rootDir, relPath);
  let text;
  try {
    text = fs.readFileSync(abs, "utf8");
  } catch {
    return [];
  }
  const baseDir = path.dirname(relPath);
  const found = new Set();
  const linkPattern = /\[[^\]]*\]\(([^)\s]+)\)/g;
  let match;
  while ((match = linkPattern.exec(stripFences(text))) !== null) {
    const target = match[1];
    if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(target)) continue;
    if (target.startsWith("/") || target.startsWith("#")) continue;
    const filePart = target.split("#")[0].split("?")[0];
    if (!filePart) continue;
    let resolved = path.posix.normalize(path.posix.join(baseDir === "." ? "" : baseDir, filePart));
    if (resolved.startsWith("..")) continue;
    // A bare directory link resolves to that directory's index.md, matching validate.sh.
    if (!/\.[^./]+$/.test(resolved)) {
      const asIndex = path.posix.join(resolved, "index.md");
      if (trackedSet.has(asIndex)) resolved = asIndex;
    }
    if (resolved === relPath) continue;
    if (trackedSet.has(resolved)) found.add(resolved);
  }
  return [...found];
}

// Which source file a node belongs to. graphify has used more than one key for this across
// versions, so accept the known spellings rather than silently reporting zero coverage.
function nodeSource(node) {
  return node.source_file || node.source || node.file || "";
}

// Compare ids modulo leading/trailing underscores. A path like `.claude/agents/pm.md` stems to
// `claude_agents_pm` here but graphify keeps the leading separator (`_claude_agents_pm`). That is
// a spelling difference, not a forked identity, and treating it as one would send the repair pass
// after nodes that are already correct.
function normalizeId(id) {
  return String(id || "").replace(/^_+|_+$/g, "");
}

// Suffixes seen on "whole document" nodes. `_doc` is the semantic tier's undocumented spelling —
// it appears in no prompt graphify ships — and `_adr` shows up where a citing file minted a node
// for the document it was citing. Both mean "this node IS that file".
const DOCUMENT_SUFFIXES = ["_doc", "_adr", "_ports", "_md"];

// Is this node a fork of some OTHER tracked file — i.e. does its id name a document it did not
// come from? Returns that file, or null. This is the defect that makes the graph lie: edges land
// on the phantom while the real document's node sits at degree 0, answering nothing.
function forkTargetFor(node, stemToFile) {
  const src = nodeSource(node);
  if (!src || !src.endsWith(".md")) return null;
  const ownStem = normalizeId(stemFor(src));
  const id = normalizeId(node.id);
  if (id === ownStem || id.startsWith(ownStem + "_")) return null;

  const candidates = [id];
  for (const suffix of DOCUMENT_SUFFIXES) {
    if (id.endsWith(suffix)) candidates.push(id.slice(0, -suffix.length));
  }
  for (const candidate of candidates) {
    const file = stemToFile.get(candidate);
    if (file && file !== src) return file;
  }
  return null;
}

// Map every tracked file to the id a conforming node for it would carry.
function buildStemIndex(trackedFiles) {
  const stemToFile = new Map();
  for (const file of trackedFiles) stemToFile.set(normalizeId(stemFor(file)), file);
  return stemToFile;
}

function endpointId(endpoint) {
  if (endpoint && typeof endpoint === "object") return endpoint.id || "";
  return endpoint || "";
}

// What the graph has SEEN. graphify's own change detection hashes each file's content
// (`_md5_file` in graphify/detect.py) and stamps a file only when its extraction actually produced
// output (upstream #2015). graphify keeps that record in graphify-out/manifest.json, which this
// repo does not commit (its mtime/seen fields churn on every run), so loom keeps the same hashes
// in a small committed file graphify never writes. A content hash — unlike the commit SHA this
// replaced — survives rebase, squash and a fresh clone.
const STAMPS_PATH = path.join("graphify-out", "extracted.json");

function contentHash(rootDir, relPath) {
  return crypto.createHash("md5").update(fs.readFileSync(path.join(rootDir, relPath))).digest("hex");
}

// The recorded hashes, or null when the record is missing or unreadable — callers fail closed.
function loadStamps(rootDir) {
  try {
    const data = JSON.parse(fs.readFileSync(path.join(rootDir, STAMPS_PATH), "utf8"));
    return data && data.files && typeof data.files === "object" ? data.files : null;
  } catch {
    return null;
  }
}

// Sorted keys, and no entries for files that no longer exist, so the record diffs cleanly.
function writeStamps(rootDir, files) {
  const kept = Object.keys(files)
    .filter((f) => fs.existsSync(path.join(rootDir, f)))
    .sort();
  const out = { files: Object.fromEntries(kept.map((f) => [f, files[f]])) };
  fs.writeFileSync(path.join(rootDir, STAMPS_PATH), JSON.stringify(out, null, 2) + "\n");
}

// Each tracked file whose current content is not the content the graph last extracted.
function staleFiles(rootDir, tracked, stamps) {
  const stale = [];
  for (const file of tracked) {
    const seen = stamps[file];
    if (!seen) {
      stale.push(`${file}  (never extracted)`);
      continue;
    }
    let now;
    try {
      now = contentHash(rootDir, file);
    } catch {
      continue;
    }
    if (now !== seen) stale.push(`${file}  (changed since extracted)`);
  }
  return stale;
}

module.exports = {
  STAMPS_PATH,
  contentHash,
  loadStamps,
  writeStamps,
  staleFiles,
  stemFor,
  loadGraph,
  trackedMarkdown,
  outboundLinks,
  nodeSource,
  endpointId,
  gitLines,
  stripFences,
  normalizeId,
  forkTargetFor,
  buildStemIndex,
  DOCUMENT_SUFFIXES,
};
