import * as vscode from "vscode";
import { SessionContextManager } from "../context";

interface CheckpointInput {
  summary: string;
  progress?: number;
  completedWork?: string[];
  remainingWork?: string[];
  keyDecisions?: string[];
}

export class CheckpointTool
  implements vscode.LanguageModelTool<CheckpointInput>
{
  constructor(private contextManager: SessionContextManager) {}
  async invoke(
    options: vscode.LanguageModelToolInvocationOptions<CheckpointInput>,
    token: vscode.CancellationToken
  ): Promise<vscode.LanguageModelToolResult> {
    const { summary, progress, completedWork, remainingWork, keyDecisions } =
      options.input;

    try {
      await this.saveCheckpoint({
        summary,
        progress: progress ?? 0,
        completedWork: completedWork ?? [],
        remainingWork: remainingWork ?? [],
        keyDecisions: keyDecisions ?? [],
      });

      return new vscode.LanguageModelToolResult([
        new vscode.LanguageModelTextPart(
          `✅ Checkpoint saved to .context/CHECKPOINT.md\n\nSummary: ${summary}\nProgress: ${
            progress ?? 0
          }%`
        ),
      ]);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown error";
      return new vscode.LanguageModelToolResult([
        new vscode.LanguageModelTextPart(
          `❌ Failed to save checkpoint: ${message}`
        ),
      ]);
    }
  }

  private async saveCheckpoint(data: {
    summary: string;
    progress: number;
    completedWork: string[];
    remainingWork: string[];
    keyDecisions: string[];
  }): Promise<void> {
    const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
    if (!workspaceFolder) {
      throw new Error("No workspace folder open");
    }

    const contextDir = vscode.Uri.joinPath(workspaceFolder.uri, ".context");
    const checkpointPath = vscode.Uri.joinPath(contextDir, "CHECKPOINT.md");

    // Ensure .context directory exists
    try {
      await vscode.workspace.fs.createDirectory(contextDir);
    } catch {
      // Directory may already exist
    }

    const content = this.formatCheckpoint(data);
    await vscode.workspace.fs.writeFile(
      checkpointPath,
      Buffer.from(content, "utf-8")
    );
  }

  private formatCheckpoint(data: {
    summary: string;
    progress: number;
    completedWork: string[];
    remainingWork: string[];
    keyDecisions: string[];
  }): string {
    const now = new Date().toISOString().split("T")[0];

    let md = `# 📍 CHECKPOINT

**Date**: ${now}
**Progress**: ${data.progress}%

---

## Summary
${data.summary}

`;

    if (data.completedWork.length > 0) {
      md += `## Completed Work\n`;
      data.completedWork.forEach((item) => {
        md += `- ✅ ${item}\n`;
      });
      md += "\n";
    }

    if (data.remainingWork.length > 0) {
      md += `## Remaining Work\n`;
      data.remainingWork.forEach((item) => {
        md += `- [ ] ${item}\n`;
      });
      md += "\n";
    }

    if (data.keyDecisions.length > 0) {
      md += `## Key Decisions\n`;
      data.keyDecisions.forEach((item) => {
        md += `- ${item}\n`;
      });
      md += "\n";
    }

    md += `---
*Generated by Context Engineering extension*
`;

    return md;
  }
}
